@Library("jenkins-shared-library")_

env.MAVEN_CENTRAL="${MAVEN_CENTRAL_COMMON}"
env.MAPR_CENTRAL="${MAPR_CENTRAL_COMMON}"
env.MAPR_RELEASES_REPO="${MAPR_RELEASES_REPO_COMMON}"
env.MAPR_SNAPSHOTS_REPO="${MAPR_SNAPSHOTS_REPO_COMMON}"
env.MAPR_MAVEN_REPO="${MAPR_SNAPSHOTS_REPO_COMMON}"

ARTIFACTORY_SERVER=''
env.REPOSITORY_NAME=''
env.GIT_REPO_URL=''
env.GIT_SHORT_COMMIT_SHA=''
env.CURRENT_BUILD_TAG=''
env.BUILD_BY_TAG=false

env.ARTIFACTORY_PATH_RPM=''
env.ARTIFACTORY_PATH_DEB=''
env.ID=''
env.MAKEFILE_ARGS=''
env.PROJECT=''
env.COMPONENT_VERSION=''
REPOSITORY_ID=''
MEP_VER=''

MAKEFILE_ARG_BRANCH_NAME = " DRILLINTERNAL_BRANCH_NAME"

pipeline {
  agent none
  triggers {
    pollSCM 'H/5 * * * *'
  }
  options {
    skipDefaultCheckout()
    disableConcurrentBuilds()
    timestamps()
  }
  parameters {
    choice(name: 'BUILD_TYPE', choices: ['Dev','EBF','Release'], description: 'default - Dev. EBF and Release args you can use only in release branches')
    string(name: 'MAKEFILE_ENV_VARS', defaultValue: '', description: 'Variables you can pass to makefile (command will be: make {THIS VAR} {project-name}). Please DO NOT put component_branch_name')
  }
  stages {
    stage("Setup settings and variables") {
      agent {label "redhat8"}
      steps {
        println "Setup variables & passwords"
        script {
          ARTIFACTORY_SERVER = Artifactory.server 'artifactory.devops.lab'
          //MAKEFILE_ARG_BRANCH_NAME will use for makefile only for release/EBF branches
          initVariables(params.BUILD_TYPE, MAKEFILE_ARG_BRANCH_NAME)
          env.MAPR_CENTRAL = "http://repository.mapr.com/maven"
          if(params.BUILD_TYPE=="Dev") {
            REPOSITORY_ID="mapr-snapshots"
          }else {
            REPOSITORY_ID="mapr-releases"
          }
        }
      }
    }

    stage ("Main CI process") {
      parallel {
        stage("Ubuntu build") {
          agent {label "ubuntu"}
          stages {
            stage("Checkout") {
              steps {
                script {
                  checkout scm
                }
              }
            }

            stage("Build") {
              steps {
                script {
                  configFileProvider([configFile(fileId: 'maven_settings', variable: 'mvn_settings')]) {
                    sh "cat ${env.mvn_settings} > settings.xml"
                  }
                  withCredentials([usernamePassword(credentialsId: 'artifactory_user_pass', passwordVariable: 'pass', usernameVariable: 'user')]) {
                    docker.image("docker.artifactory.lab/ubuntu16-java11:drill-1.16.1").inside (
                    "-e MAPR_MIRROR=${MAPR_MIRROR} \
                    -e MAPR_CENTRAL=${MAPR_CENTRAL} \
                    -e MAVEN_CENTRAL=${MAVEN_CENTRAL} \
                    -e MAPR_MAVEN_REPO=${MAPR_MAVEN_REPO} \
                    -e BUILD_NUMBER=${ID}.${BUILD_NUMBER} \
                    -e MAPR_RELEASES_REPO=${MAPR_RELEASES_REPO} \
                    -e MAPR_SNAPSHOTS_REPO=${MAPR_SNAPSHOTS_REPO} \
                    -e REPOSITORY_ID=${REPOSITORY_ID} \
                    -v /root/.m2:/root/.m2:rw \
                    -v /root/yum-proxy.conf:/etc/yum.conf:ro \
                    -v /etc/hosts:/etc/hosts:ro \
                    -v /root/apt-proxy.conf:/etc/apt/apt.conf.d/proxy.conf:ro \
                    -v /root/.gradle/gradle.properties:/root/.gradle/gradle.properties:ro \
                    -v /etc/profile.d/proxy.sh:/etc/profile.d/proxy.sh:ro \
                    -v /etc/localtime:/etc/localtime:ro \
                    -v /root/.ssh:/root/.ssh:rw \
                    -v ${WORKSPACE}/settings.xml:/root/.m2/settings.xml:ro") {
                      sh """
                        rm -rf ${PROJECT}; git clone git@github.com:mapr/private-pkg.git ${PROJECT}; \
                        cd ${PROJECT}; \
                        git checkout MEP-4.0.0 ; \
                        make mapr-drill-internal-${COMPONENT_VERSION} ${MAKEFILE_ARGS} TIMESTAMP=${ID} DRILL_COMMIT_ID=${GIT_SHORT_COMMIT_SHA} ; \
                        make ${PROJECT} ${MAKEFILE_ARGS} TIMESTAMP=${ID} DRILL_COMMIT_ID=${GIT_SHORT_COMMIT_SHA}; \
                        make mapr-drill-yarn-${COMPONENT_VERSION} ${MAKEFILE_ARGS} TIMESTAMP=${ID} DRILL_COMMIT_ID=${GIT_SHORT_COMMIT_SHA} ; \
                        make mapr-drill-internal-${COMPONENT_VERSION}-deploy ${MAKEFILE_ARGS} TIMESTAMP=${ID} DRILL_COMMIT_ID=${GIT_SHORT_COMMIT_SHA} ; \
                      """
                    }
                  }
                }
              }
            }

            stage("Upload to Artifactory") {
              steps{
                script {
                  from = "${WORKSPACE}/${env.PROJECT}/dist/*"
                  to = "${env.ARTIFACTORY_PATH_DEB}"
                  props = "deb.distribution=binary;deb.component=trusty;deb.architecture=all;release=${params.BUILD_TYPE}"
                  artifactory.uploadArtifactsAndBuildInfo(ARTIFACTORY_SERVER, from, to, props)
                }
              }
            }
          }
        }

        stage("Redhat build") {
          agent { label "redhat8" }
          stages {
            stage("Checkout") {
              steps {
                script {
                  checkout scm
                }
              }
            }

            stage("Build") {
              steps {
                script {
                  configFileProvider([configFile(fileId: 'maven_settings', variable: 'mvn_settings')]) {
                    sh "cat ${env.mvn_settings} > settings.xml"
                  }
                  withCredentials([usernamePassword(credentialsId: 'artifactory_user_pass', passwordVariable: 'pass', usernameVariable: 'user')]) {
                    docker.image("docker.artifactory.lab/centos8-java11-gcc8:drill-1.16.1-temp").inside (
                    "-e MAPR_MIRROR=${MAPR_MIRROR} \
                    -e MAPR_CENTRAL=${MAPR_CENTRAL} \
                    -e MAVEN_CENTRAL=${MAVEN_CENTRAL} \
                    -e MAPR_MAVEN_REPO=${MAPR_MAVEN_REPO} \
                    -e BUILD_NUMBER=${ID}.${BUILD_NUMBER} \
                    -e MAPR_RELEASES_REPO=${MAPR_RELEASES_REPO} \
                    -e MAPR_SNAPSHOTS_REPO=${MAPR_SNAPSHOTS_REPO} \
                    -e REPOSITORY_ID=${REPOSITORY_ID} \
                    -v /root/.m2:/root/.m2:rw \
                    -v /root/yum-proxy.conf:/etc/yum.conf:ro \
                    -v /etc/hosts:/etc/hosts:ro \
                    -v /root/apt-proxy.conf:/etc/apt/apt.conf.d/proxy.conf:ro \
                    -v /root/.gradle/gradle.properties:/root/.gradle/gradle.properties:ro \
                    -v /etc/profile.d/proxy.sh:/etc/profile.d/proxy.sh:ro \
                    -v /etc/localtime:/etc/localtime:ro \
                    -v /root/.ssh:/root/.ssh:rw \
                    -v ${WORKSPACE}/settings.xml:/root/.m2/settings.xml:ro") {
                      sh """
                        rm -rf ${PROJECT}; git clone git@github.com:mapr/private-pkg.git ${PROJECT}; \
                        cd ${PROJECT}; \
                        git checkout MEP-4.0.0 ; \
                        make mapr-drill-internal-${COMPONENT_VERSION} ${MAKEFILE_ARGS} TIMESTAMP=${ID} DRILL_COMMIT_ID=${GIT_SHORT_COMMIT_SHA} ; \
                        make ${PROJECT} ${MAKEFILE_ARGS} TIMESTAMP=${ID} DRILL_COMMIT_ID=${GIT_SHORT_COMMIT_SHA}; \
                        make mapr-drill-yarn-${COMPONENT_VERSION} ${MAKEFILE_ARGS} TIMESTAMP=${ID} DRILL_COMMIT_ID=${GIT_SHORT_COMMIT_SHA} ; \
                        make mapr-drill-internal-${COMPONENT_VERSION}-deploy ${MAKEFILE_ARGS} TIMESTAMP=${ID} DRILL_COMMIT_ID=${GIT_SHORT_COMMIT_SHA} ; \
                      """
                    }
                  }
                }
              }
            }

            stage("RPM Sign") {
              steps {
                configFileProvider([configFile(fileId: 'rpmSignSh', variable: 'rpmSignSh')]) {
                  sh """
                  cat ${env.rpmSignSh} > rpm_sign.sh
                  chmod 765 rpm_sign.sh
                  ./rpm_sign.sh ${PROJECT}/dist
                  """
                }
              }
            }

            stage("Upload to Artifactory") {
              steps{
                script {
                  from = "${WORKSPACE}/${PROJECT}/dist/*"
                  to = "${ARTIFACTORY_PATH_RPM}"
                  props = "release=${params.BUILD_TYPE}"
                  artifactory.uploadArtifactsAndBuildInfo(ARTIFACTORY_SERVER, from, to, props)
                }
              }
            }

            stage("Whitesource scan") {
              steps {
                script {
                  withCredentials([string(credentialsId: 'wsApiKey', variable: 'wsApiKey'), string(credentialsId: 'wsUserKey', variable: 'wsUserKey')]) {
                    //Launch container with WS scan. After scan report will upload to WS site
                    docker.image("docker.artifactory/whitesource:0.0.1").inside (
                      "-e MAPR_MIRROR=${MAPR_MIRROR} \
                      -e MAPR_CENTRAL=${MAPR_CENTRAL} \
                      -e MAVEN_CENTRAL=${MAVEN_CENTRAL} \
                      -e MAPR_MAVEN_REPO=${MAPR_MAVEN_REPO} \
                      -e MAPR_RELEASES_REPO=${MAPR_RELEASES_REPO} \
                      -e MAPR_SNAPSHOTS_REPO=${MAPR_SNAPSHOTS_REPO} \
                      -v /root/yum-proxy.conf:/etc/yum.conf:ro \
                      -v /etc/hosts:/etc/hosts:ro \
                      -v /root/apt-proxy.conf:/etc/apt/apt.conf.d/proxy.conf:ro \
                      -v /root/.gradle/gradle.properties:/root/.gradle/gradle.properties:ro \
                      -v /etc/profile.d/proxy.sh:/etc/profile.d/proxy.sh:ro \
                      -v /root/.ssh:/root/.ssh:rw \
                      -v ${WORKSPACE}/settings.xml:/root/.m2/settings.xml:ro \
                      -v /root/.m2/repository:/root/.m2/repository:rw") {
                        sh """
                        cd devops/whitesource/ ; \
                        curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar ; \
                        java -jar wss-unified-agent.jar -project ${PROJECT} -product ${PROJECT} -userKey $wsUserKey -apiKey $wsApiKey -c wss-unified-agent.config -d ../../ ; \
                        """
                      }
                   }
                }
              }
            }

            stage("Push Whitesource reports") {
              steps {
                script {
                  withCredentials([string(credentialsId: 'wsApiKey', variable: 'wsApiKey'), string(credentialsId: 'wsUserKey', variable: 'wsUserKey')]) {
                    catchError {
                      /*Get token of product. We have to communicate with WS API only using 64-digits project's token.
                        We are sending request to API and get ALL "project+token" pairs. Then parse this information and find token for current project*/
                        productToken = ws.getWSProductToken(PROJECT)

                        //Get reports (Excel and json) from WS site and save these reports to files. Once for each format
                        ws.getWSReports(productToken)

                        //Move latest reports to the "old" folder in Artifactory
                        ws.moveOldWsReports(ARTIFACTORY_SERVER)

                        //Upload reports (Excel and json) to the Artifactory (to the latest folder)
                        ws.uploadToArtifactory(ARTIFACTORY_SERVER)
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  post {
    failure {
      script {
        postActions.failure()
      }
    }
    fixed {
      script {
        postActions.fixed()
      }
    }
    aborted {
      script {
        postActions.aborted()
      }
    }
    always {
      script {
        postActions.always()
      }
    }
  }
}
